driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.9
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.7
  - name: fedora-25
  - name: opensuse-leap-42.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: windows-2008r2 # private Chef Software Inc. image
    driver_config:
      box: chef/windows-server-2008r2-standard
  - name: windows-2012r2 # private Chef Software Inc. image
    driver_config:
      box: chef/windows-server-2012r2-standard

suites:
  - name: json_file
    run_list: chef_handler::json_file
  - name: custom_resource
    run_list: test::default
