driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.7
  - name: freebsd-10.3
  - name: freebsd-11.0
  - name: fedora-25
  - name: opensuse-leap-42.2
  - name: ubuntu-14.04
  - name: ubuntu-14.04-chef127
    driver_config:
      box: bento/ubuntu-14.04
    provisioner:
      require_chef_omnibus: 12.7.2
  - name: ubuntu-16.04
  - name: windows-2008r2
    driver_config:
      box: chef/windows-server-2008r2-standard
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard

suites:
- name: default
  run_list:
    - recipe[ohai_test::default]
