---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.9
  - name: debian-8.2
  - name: fedora-21
  - name: fedora-22
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04


suites:
  - name: default
    run_list:
      # Needed for Foodcritic RACK004
  - name: gem
    run_list:
      - recipe[slack_handler]
    attributes:
      chef_client:
        handler:
          slack:
            team: foo
            api_key: bar
  - name: webhook
    run_list:
      - recipe[slack_handler]
    attributes:
      chef_client:
        handler:
          slack:
            team: foo
            api_key: bar
            webhooks:
              name:
                - test
              test:
                url: https://hooks.slack.local/1/2/3
