AllCops:
  Exclude:
    - tmp/**/*
    - Rakefile

Lint/RescueException:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
